<?php

/**
 * Secret Server
 * This is an API of a secret service. You can save your secret by using the API. You can restrict the access of a secret after the certen number of views or after a certen period of time.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Secret Server
 * @version 1.0.0
 */

$app = app();

$router->get('/', function () use ($app) {
    return $app->version();
});

/**
 * post addSecret
 * Summary: Add a new secret
 * Notes: 
 * Output-Formats: [application/json, application/xml]
 */
$router->post('/v1/secret', 'SecretApi@addSecret');
/**
 * get getSecretByHash
 * Summary: Find a secret by hash
 * Notes: Returns a single secret
 * Output-Formats: [application/json, application/xml]
 */
$router->get('/v1/secret/{hash}', 'SecretApi@getSecretByHash');
